name: tasktaker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.2

  # Core
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0
  provider: ^6.1.2
  http: ^1.2.2

  # PDF & File handling
  file_picker: ^8.1.4
  syncfusion_flutter_pdf: ^28.1.33
 

  # Notifications
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  permission_handler: ^11.3.1
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/splash.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#14B8A6"
  image: assets/splash.png
  android: true
  ios: true
  android_gravity: center
